### ISSUE TITLE
One Day Off on Daylight Saving Time

### ISSUE THREAD

**Issue by high42** [taitems/jQuery.Gantt#203] opened 2016-04-26 00:10 UTC
First of all, congratulations on this awesome library :)

To begin, I am working with Mexico's CST (Central Stanard Time) and CDT (Central Daylight Time) which you can see [here](http://www.timeanddate.com/time/zone/mexico/mexico-city).

The problem I ran into was that when a task starts before the timezone change in spring (April 3rd) the end date (to) is one day short. I found the problem to be when looping through the values of each data element and setting a row in the Fill the Chart section.

So each time a bar is created we have the following line of code:

`_bar = core.createProgressBar(dl, day);`

That means that dl (duration) sets the width of the bar with the following line of code:

`dl = Math.round((cTo - cFrom) / tools.getCellSize()) + 1;`

However, for a specific case (default case in switch) the calculation is the following:

`dl = Math.floor((dTo - dFrom) / UTC_DAY_IN_MS) + 1;`

In this specific case, the Math.floor function is taking for example a 12.958333333333334 to a 12. So the solution for this specific case would be to use Math.Round();

I wanted to post this here to see why we're rounding down in that specific case. What does it aim to do? I don't know if using Math.Round() will mess with something else...

**Comment by smb** [comment] 2016-05-19 10:00
i had the same problem and initially changed it to ceil first which caused it to error (1 extra day calculated/painted) if you have an data element from sept -> nov because of the second DST change.

so changing it to round seems to fix it for me (i only use daily view)

**Comment by usmonster** [comment] 2018-02-24 12:23
Hello, from 2018! Sorry for the massive delay in responding, but this seems to be a duplicate of #95 and #41, so I'll close this one for now. Please feel free to follow the other issues until a fix is implemented.

**Closed by usmonster** 2018-02-24 12:23 UTC
