### ISSUE TITLE
Gantt Chart within Jquery Tabs

### ISSUE THREAD

**Issue by justbaron** [taitems/jQuery.Gantt#194] opened 2016-01-08 12:30 UTC
Sample code doesn't seem to work correctly when included within a JQuery tab element.
Everything but the date/time grid is rendered.
When you zoom in/out, the grid then appears.
See below, same graph within/outside a JQuery tab.
![capture](https://cloud.githubusercontent.com/assets/16609488/12197918/4fc0635a-b603-11e5-877a-b0c1d9aa0051.jpg)

**Comment by usmonster** [comment] 2016-01-08 13:36
This seems like a duplicate of #48. I'll close this one for now, but let me know on #48 if my last comment there is helpful to you and I'll respond there. Thanks!

**Closed by usmonster** 2016-01-08 13:36 UTC
