### ISSUE TITLE
Graphic Problem

### ISSUE THREAD

**Issue by LuigiMdg** [taitems/jQuery.Gantt#221] opened 2018-03-04 12:22 UTC
Hi..
Today I've this problem..! (May is on new line)
[Link to Image](https://pasteboard.co/HakVN1l.png)
This using original _js_ and _css_

**Comment by usmonster** [comment] 2018-03-04 12:27
Hello! Thanks for reporting this. Can you please provide a [JSFiddle](https://jsfiddle.net/) that reproduces the problem?

**Comment by LuigiMdg** [comment] 2018-03-04 12:27
I've found the problem..
February is displayed, with width of 0px, but they deal 1px..
If I take a _css display:none_ it's ok
[Link to HTML and CSS](https://pasteboard.co/HakXOln.png)

**Comment by usmonster** [comment] 2018-03-06 00:24
Thanks for the test. You're right—it looks like a problem in the header rendering logic for the "days" scale.

For some reason unclear to me, there's [an extra day](https://github.com/taitems/jQuery.Gantt/blob/master/js/jquery.fn.gantt.js#L710) prepended to the header's range, which causes this issue on specific dates in the beginning of each month. I think it was added to compensate for another [workaround introduced 5 years ago](https://github.com/taitems/jQuery.Gantt/commit/90e76283#diff-68db7efe596172a1806bc03207a052a6R675). Maybe @kripper or @taitems can comment?

In any case, I just put up a potentially cleaner, moderately-tested [fix for this](https://github.com/taitems/jQuery.Gantt/compare/master...usmonster:master) along with some long-standing DST-related issues (#95, #41) [on my personal branch](https://github.com/usmonster/jQuery.Gantt). Please take a look and test to see if it works for you, and I'll make a PR & eventually merge it to the official source.

**Comment by LuigiMdg** [comment] 2018-03-06 18:22
No.. The problem isn't a extra day.. The problem is February that have width = 0px.. If you can delete the print of the months with 0 pixels they work correctly

**Comment by usmonster** [comment] 2018-03-06 18:30
I'll clarify what I mean—there's some strange logic that compares the chart's range with the "day before" its actual start. These comparisons to a seemingly irrelevant day can cause an extra month or year header cell to appear, even if no day in the range is part of the month/year.

@LuigiMdg, can you please test if my fix works for you by using [this file](https://rawgit.com/usmonster/jQuery.Gantt/master/js/jquery.fn.gantt.js)? Thanks in advance!

**Comment by LuigiMdg** [comment] 2018-03-06 19:19
Today it work without use you file..! :(
I wait next time error to try your updated file..
Another question, I can set the bars in the middle of grid cells?

**Comment by LuigiMdg** [comment] 2018-04-04 15:36
The problem has finally arisen ..!
I made a video of how I would solve it .. Simply, when the width is equal to zero, you should avoid giving the output ..
Alternatively, a **display** could be set to **none**
[https://youtu.be/wdF_9KUTSpE](Click for Video)

**Comment by usmonster** [comment] 2018-04-04 16:37
Hello again! :)

As I mentioned in my previous two comments, I've already made a potential fix for this issue.

Can you please test it by temporarily loading [this file](https://rawgit.com/usmonster/jQuery.Gantt/master/js/jquery.fn.gantt.js) in your page instead of the official one from this repository, and then tell me if it works for you?

Alternatively, you can play around with this JSFiddle, which demonstrates the fix:
https://jsfiddle.net/xpvt214o/46353/

Please let me know if there are any unwanted side effects of my fix, and I'll update it. Otherwise, if it works, I'll make a pull request and get it merged into the official plug-in right away.

Thanks again for reporting this!

**Comment by LuigiMdg** [comment] 2018-04-04 23:29
I could not explain why copying the code generated on the test page could not reproduce the problem ..
I know so much that it was your fix that adjusted everything ..!
Now it is gone, but as soon as it appears again I try to load it and I can confirm if the problem is solved :+1:

**Comment by usmonster** [comment] 2019-01-06 21:41
I finally put my fix into a pull request: #226.

Please feel free to review it and test it out!

This issue will be closed once it's merged.

**Comment by usmonster** [comment] 2019-02-11 09:41
#226 was merged, so I'm closing this. :)

**Closed by usmonster** 2019-02-11 09:41 UTC
Labels: bug, needs input
