### ISSUE TITLE
Box sizing not aligned in line with the weeks and days hence reflection a wrong date on chart.

### ISSUE THREAD

**Issue by chaituyb** [taitems/jQuery.Gantt#206] opened 2016-07-08 10:17 UTC
hi,
I want to point an issue with the plug-in the weeks and days are not aligned with the box.so the box reflects a wrong date to the user. please look at the below image to have a clear picture regarding this issue.
![image](https://cloud.githubusercontent.com/assets/20354219/16684428/50a70ad0-4505-11e6-98f8-9ed706897e9e.png)

the tool tip shows the exact date i.e 2016/10/21 but the weeks and days view is not in align.i am using chrome browser.and these are the setting for the gantt.
                itemsPerPage:2,
                scale: "days",
                 maxScale: "months",
                minScale: "days",
i also face problem in loading the plug-in the events are only displayed only on clicking the " + " button.

**Comment by usmonster** [comment] 2016-07-09 08:18
Hi @chaituyb! Thanks for the report. It looks like you might be using Bootstrap. If so, this is very likely a duplicate of #102 (see workaround in 2666f30).

Please try it out, and if it doesn't fix it I can reopen the issue. (Closing it for now.)

**Comment by chaituyb** [comment] 2016-07-13 10:48
Thank you so much it is working now.... 
![image](https://cloud.githubusercontent.com/assets/20354219/16800929/0ed46fa2-48f8-11e6-88f7-541706942a46.png)

But the events are only displayed only on clicking the " + " button.There are no events on load.
The settings for the gantt.
itemsPerPage:10,
scale: "days",
maxScale: "months",
minScale: "days",

**Comment by usmonster** [comment] 2016-07-13 11:49
Ok, this might be a different issue--reopened.

@chaituyb can you please provide a JSFiddle that demonstrates the problem?

**Comment by chaituyb** [comment] 2016-07-14 08:30
https://jsfiddle.net/sg4vjp6a/1/

please check this javascript fiddle.

**Comment by chaituyb** [comment] 2016-07-14 11:23
@usmonster the problem has been solved.Thanks a lot for your support.

**Comment by usmonster** [comment] 2016-07-14 15:59
@chaituyb Glad I could help. ;) Re-closing the issue now.

**Closed by usmonster** 2016-07-14 15:59 UTC
