### ISSUE TITLE
Duplicate icons on buttons?

### ISSUE THREAD

**Issue by rgbinnovation** [taitems/jQuery.Gantt#232] opened 2019-08-13 02:50 UTC
Hi, I'm getting duplicate buttons on icons? Has anyone seen this before?

<img width="981" alt="Screen Shot 2019-08-13 at 10 47 09" src="https://user-images.githubusercontent.com/3257827/62911777-29893200-bdb8-11e9-9af4-956037571fcf.png">

**Comment by usmonster** [comment] 2019-08-13 15:24
Hi @rgbinnovation! Thanks for reporting this. It looks & sounds similar to #230, caused by some CSS interference by bootstrap.

Can you please create a jsFiddle that demonstrates this issue? It will help to know if it's an issue on the plug-in's side or elsewhere. Thanks!

**Comment by carolag15** [comment] 2019-09-30 15:07
Any solution to this issue? I have the same issue and the days rows are
![example](https://user-images.githubusercontent.com/44947445/65891425-65924980-e39c-11e9-8ae9-603211b20b72.png)

**Comment by usmonster** [comment] 2019-10-06 12:18
Hi @carolag15! Please see [my previous comment](https://github.com/taitems/jQuery.Gantt/issues/232#issuecomment-520882381). :)

If you can provide more information (eg., are you using Bootstrap? If so, what version?), or provide a link to a live page that demonstrates the issue (screenshots aren't as helpful), then I might be able to answer you.

Since there has been no new information in a couple months, I'll close this issue for now. I may reopen it if there's more information.

Thanks for reporting the issue!

**Closed by usmonster** 2019-10-06 12:18 UTC
Labels: needs input

**Comment by quevon24** [comment] 2021-04-12 23:13
Thanks for the plugin, the problem is with bootstrap class: nav-link with the padding, that's what makes the icon duplicates

.nav-link {
    display: block;
    padding: .5rem 1rem;
}
