### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by dhananjaygoel** [taitems/jQuery.Gantt#179] opened 2015-07-09 12:25 UTC
If your screen resolution is higher, then the gantt when scrolled in the middle moves a bit.

**Comment by dhananjaygoel** [comment] 2015-07-29 08:08
@taitems any help?

**Comment by usmonster** [comment] 2015-07-29 11:47
Hi @dhananjaygoel! Can you please provide more information? What OS and screen resolution? On which browsers to you see this? Can you also provide a simple jsFiddle where the issue can be reproduced?

**Comment by dhananjaygoel** [comment] 2015-07-29 11:52
I'm using Windows Vista/Chrome and when I am at 75% zoom, it shows as attached. I'm looking at the demo here - http://taitems.github.io/jQuery.Gantt/

![gantt-issue](https://cloud.githubusercontent.com/assets/2780489/8956731/5ec17c62-3616-11e5-8f45-2994ef3c56ef.jpg)

**Comment by dhananjaygoel** [comment] 2015-07-29 11:57
@usmonster 

In the demo, if I scroll a bit right in Dec 2011, on normal resolution, it shows:

![normal-resolution-gantt-issue](https://cloud.githubusercontent.com/assets/2780489/8956782/c869c804-3616-11e5-8fa4-4772122a9bbb.jpg)

When I press (CTRL + -) to 75%, it shows:

![75pc-resolution-gantt-issue](https://cloud.githubusercontent.com/assets/2780489/8956781/c8694028-3616-11e5-9cd6-a619103377ac.jpg)

If you see it has moved from 14 dec to 13 dec.

**Comment by usmonster** [comment] 2015-07-29 12:25
Thanks for the thorough description and screenshots! This might be an interaction issue with the Bootstrap reset, and the the demo page unfortunately doesn't yet handle this, though it's planned in #102--please follow that to be updated when it's fixed. In the meantime, you can also see #32 & #51 for some history and a workaround.

I'll close this issue since it's a duplicate, but please let me know if the issue is still a problem on your own page after you try the workaround, and I will reopen it. Thanks again!

**Closed by usmonster** 2015-07-29 12:25 UTC

**Comment by dhananjaygoel** [comment] 2015-07-29 12:33
Thanks. Is https://github.com/taitems/jQuery.Gantt/commit/2666f300fa68af899361a975952fe00a200df5ef the workaround?

**Comment by dhananjaygoel** [comment] 2015-07-29 12:43
Also, I tried adding in my page, but it doesn't seem to fix it.

**Comment by usmonster** [comment] 2015-07-29 16:35
Yes, that was the workaround, though if that didn't fix the issue, you should subscribe to issues #51 and #102 and see if your problem goes away when these are fixed. If you want to further troubleshoot on your page, please provide a publicly-accessible link to it, and I'll try to take a look later this week.

**Comment by Hermi999** [comment] 2015-08-31 09:21
Hi, 
I've been reading through all the issues corresponding to this "Zoom-Issue" & I'm wondering if there is a solution available yet?
I guess this issue is still open, since I get the above described behavior when I download the Master branch and open the index.html file.

Am I right or did I miss something? Is there a reliable solution out there?

**Comment by usmonster** [comment] 2017-01-08 21:15
Just a quick recap on this. There were two zoom-related issues: broken gridlines, and broken headers. The header issue should be fixed on the master branch, though #51 captures the remaining issue, which may actually be a caused by specific browser implementation issues. A workaround may or may not be implemented. Hope this helps! (Though the response is over a year late...)
