### ISSUE TITLE
Empty values can break plugin

### ISSUE THREAD

**Issue by MauroMombelli** [taitems/jQuery.Gantt#142] opened 2014-05-08 16:02 UTC
If i add one or more 'source' and none of it has 'values', the plugin break.
If even one of them as at least one 'values' it render correctly every 'source'.

example: 
[ 
{ "name" : "a", "desc" : "blabal", "id" : "24", "values" : [  ] }, 
{ "name" : "a", "desc" : "null", "id" : "25", "values" : [  ] }, 
{ "name" : "a", "desc" : "null", "id" : "23", "values" : [  ] }, 
{ "name" : "asdsa", "desc" : "null", "id" : "26", "values" : [  ] }
]

**Comment by usmonster** [comment] 2017-01-09 00:02
Hello, @MauroMombelli! I think this may have been fixed sometime in the last couple of years, or I no longer understand the issue. 😅

I can't reproduce the described behavior. Can you please check with the version on the master branch and let me know? If you still find an issue, please include a link to a JSFiddle that demonstrates the bug. Thanks!

**Comment by MauroMombelli** [comment] 2017-01-09 00:10
<3 unfortunately the project I was working on is long gone :/

The issue was (iirc) that a project with no day assigned was breaking the plugin (nothing loading).

The json in the first post was a "save" of the issue, so if that now show the calendar with the 4 project with no day assigned.. It works :)

**Comment by usmonster** [comment] 2017-01-09 07:19
Thanks for the quick feedback, @MauroMombelli! I'll close this issue, then. 👍

**Closed by usmonster** 2017-01-09 07:19 UTC
Labels: bug, needs input
