### ISSUE TITLE
Zoom Out Not Working

### ISSUE THREAD

**Issue by n0nag0n** [taitems/jQuery.Gantt#202] opened 2016-02-19 21:04 UTC
Is it just me or is zoom out not working? If you go to the demo site http://taitems.github.io/jQuery.Gantt/, zoom in, and it zooms in, but after you zoom in, you click the - button to zoom out and it says "Please Wait..." but it doesn't render anything new and looks the same as if you never clicked the button.

Tested on most recent versions of Firefox, Chrome, and Safari on a Mac El Capitan 10.11.3

**Comment by usmonster** [comment] 2016-02-19 21:28
Hi @n0nag0n! It looks like you've noticed one of the side effects of #138. The basic issue is that the min/max/default zoom scales are not sanity-checked, and that the current version of the demo on the `gh-pages` branch is not correctly configured (this is corrected on the `master` branch).

A general fix for this, along with an updated demo page, are both planned to be released in the next version. Until then, I'll close this issue as a duplicate of #138. Thanks for reporting it!

**Closed by usmonster** 2016-02-19 21:28 UTC

**Comment by n0nag0n** [comment] 2016-02-19 21:48
Ahh I missed that one in the search results. Good to know, thanks!
