### ISSUE TITLE
Generating a date width will fail if an invalid date value is entered first.

### ISSUE THREAD

**Issue by tkmry** [taitems/jQuery.Gantt#239] opened 2020-11-16 16:05 UTC
If the first object in the "source" array passed to jQuery.gantt contains incorrect date information, the calendar will fail to generate (NaN/Undefined).
These are caused by the getMinDate and getMaxDate implementations.
When the getMinDate or getMaxDate function receives incorrect date information for the first loop, the minDate/maxDate variable is assigned "Invalid Date", but the value does not change in the loop and minDate/maxDate has "Invalid Date" remains set.

I've come up with a code that solves the above problem for my personal requirements and posted a link (*Ref1) to a modified version of the function in question.
I am aware that this is a problem with jquery.gantt itself, so I am putting it up as an issue, but should I send a pull request?

*Ref1
ガントチャートプラグイン – cybozu developer network
https://developer.cybozu.io/hc/ja/articles/203716110?page=1#comment_900001456206

----
in Origin(jp)

jQuery.gantt に渡した "source" 配列の最初のオブジェクトが適切でない日付情報を保持していると、カレンダーの生成に失敗(NaN/Undefined)する。
これらはgetMinDateやgetMaxDateの実装により引き起こされている。
getMinDateやgetMaxDate関数が1ループ目の処理に不適切な日付情報を受け取ると、minDate/maxDate 変数は "Invalid Date" を代入されるが、ループの中で値が変わることはなく minDate/maxDate には "Invalid Date" がセットされたままになる。

個人的な要件で上記の問題を解決するコードを考え、該当関数の修正内容をリンク先(*Ref1)に投稿した。
この問題は jquery.gantt 自体の問題だと認識しているため、一旦issueとして立てているが、pull requestを送った方が良いだろうか？

*Ref1
ガントチャートプラグイン – cybozu developer network
https://developer.cybozu.io/hc/ja/articles/203716110?page=1#comment_900001456206

**Comment by tkmry** [comment] 2020-11-21 04:30
The snippet of this issue.
Check it, please.
```
// Common Source
    var valid_source  = {
        name: "Valid Date",
        values: [{
            from: "",
            to: "",
            label: "text",
        }]
    };
    var invalid_source = {
        name: "Invalid Date",
        values: [{
            from: "/Date(2020/10/11)/",
            to: "/Date(2020/10/12)/",
            label: "has Date",
        }]
    }
// -----
// Correct
    $(".gantt").gantt({
        source: [
            valid_source,
            invalid_source
        ],
        scale: "days",
    });
// -----
// Wrong
    $(".gantt").gantt({
        source: [
          invalid_source,
          valid_source
        ],
        scale: "days",
    });
```

**Comment by usmonster** [comment] 2020-11-22 10:26
Hi @tkmry! Thanks for using the plugin and reporting an issue here.

If I understand correctly, the issue is that the chart rendering breaks if invalid data is provided. If this is the case, then the plugin is working as designed—we prefer to "fail fast" when invalid data is given, though it's true that it might be nicer to fail more gracefully.

Still, in this case, I will close the issue and the related PR #241, if you don't mind. Please feel free to reopen the issue if I've misunderstood the issue.

Thanks again for using the plugin! (And please be sure you're using the version provided in this repo, as it has behaviors that are a bit different from the upstream repo.)

**Comment by tkmry** [comment] 2020-11-23 02:41
I am checking the operation of this repository, which is currently provided, rather than the upstream repository. Sorry for not including version information.

This case is not a problem that occurs when "invalid data is provided". It's a problem that occurs "when invalid data is provided 'at the first'".
If by design the correct behavior is to break the rendering when "invalid data is provided", then the rendering should also be broken in Pattern1 and Pattenr2 as mentioned above.
But personally, I don't want the rendering to be broken in either case.

Translated with www.DeepL.com/Translator (free version)

**Comment by tkmry** [comment] 2020-11-30 13:31
Hi, @usmonster.
I think, this issue is not resolved. 
Reopen, please.

**Comment by usmonster** [comment] 2020-11-30 13:54
Indeed, it would be better for the behavior to be consistent in any case, so I'll reopen the issue.

Can you please send me a link to a page with a working example that demonstrates the issue?

The screenshots and code are helpful, but it's much easier if you send me something like a [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/pen/) link.

Thanks!

**Comment by tkmry** [comment] 2020-11-30 15:15
Thank you for reopening.
I wrote the code for this case here, so take a look.
http://jsfiddle.net/3awxvbLs/4/

**Comment by tkmry** [comment] 2020-11-30 23:02
sample2.

fail all if invalid date value provided.
-> http://jsfiddle.net/ywrsd056/2/

Somehow generating if invalid date value provided.
http://jsfiddle.net/xt3bckgm/2/

**Comment by usmonster** [comment] 2020-11-30 23:59
Thanks for the live demo! I can now more clearly see what the issue is.

Since the plugin doesn't do strict input validation, this can lead to invalid `Date` objects being passed around. This is "fine" since we don't define what we do with invalid input, but the way we determine the bounds of the chart can lead to inconsistent rendering behavior, as already described.

After reviewing the affected code, I think the approach you suggested in #241 is a good solution, so I'll reopen it.

Thanks again for contributing!

**Comment by tkmry** [comment] 2020-12-01 00:25
Thanks for checking and review!
My problem is solved, I'll close this issue. <3

**Comment by tkmry** [comment] 2020-12-01 00:31
I misunderstood and closed it before the merge.
When I get home from work, I will correct it and send you another PR as per my review.

**Comment by usmonster** [comment] 2020-12-01 08:05
Thanks, @tkmry! You don't need to open a new PR, as it's easy to apply the suggestions in the review. I can actually apply the suggestions myself and merge the PR.

**Comment by usmonster** [comment] 2020-12-01 08:13
It's been merged, so I will close this issue. Thanks again for your contribution!

**Closed by usmonster** 2020-12-01 08:13 UTC
