### ISSUE TITLE
Bar is going out of the selected time frame.

### ISSUE THREAD

**Issue by jasjitCheema** [taitems/jQuery.Gantt#243] opened 2020-12-07 17:25 UTC
Bar is going out of the selected time frame. 

Bar from start date gets increased on Zooming. 
![Screenshot](https://user-images.githubusercontent.com/37025625/101383559-4f0c4a00-38df-11eb-81fa-274c3720bb27.png)

And end date is always showing more than saved in database

![Screenshot](https://user-images.githubusercontent.com/37025625/101382912-7f9fb400-38de-11eb-9be4-8a5de851710b.png)

**Comment by usmonster** [comment] 2020-12-07 17:44
Hello! Thanks for using this plugin and taking the time to report your issue.

To help me better troubleshoot what's happening, can you please provide a link to a working minimal demo of the problem, preferably on [JSFiddle](https://jsfiddle.net/) or similar? Thanks again!

**Comment by jasjitCheema** [comment] 2020-12-08 05:24
Please check

https://servebetter.ultimatecodesolutions.com/web/public/project-planing

First login using
admin1@gmail.com
12345678

Thanks

**Comment by usmonster** [comment] 2020-12-08 12:01
Thanks for the demo, it was very helpful in finding the cause of your issue.

I've reduced what I saw to this JSFiddle:
https://jsfiddle.net/r54x3npd/3/

As I saw in your source, the dates are given in the milliseconds format, which always translates to an absolute time. In this case, it means that the chart will render differently depending on the time zone of the viewer, which can be a desired behavior in many cases.

In your case, however, you probably mean to specify ["floating"](https://w3c.github.io/i18n-drafts/questions/qa-floating-times.en#question) dates and times so that the time will display the same everywhere. Here's an example how you could do that:
https://jsfiddle.net/r54x3npd/4/

Since this is behaving as expected, I will close this issue. Feel free to comment or reopen if necessary, and thanks again for taking the time to ask your question here.

**Closed by usmonster** 2020-12-08 12:01 UTC
